<a href="https://colab.research.google.com/github/245ansh/MLLL/blob/main/TextProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

bag of words


In [ ]:
!pip install numpy

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [3]:
bow= CountVectorizer()
bow.fit(['Hello everybody, this movie is not scary'])
bow.vocabulary_

{'hello': 1,
 'everybody': 0,
 'this': 6,
 'movie': 3,
 'is': 2,
 'not': 4,
 'scary': 5}

In [4]:
bow.transform(['']).toarray()

array([[0, 0, 0, 0, 0, 0, 0]])

In [5]:
bow.transform(['everybody scary']).toarray()

array([[1, 0, 0, 0, 0, 1, 0]])

In [6]:
bow.fit_transform(['hello everyone', 'everyone good','good day']).toarray()

array([[0, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 1, 0]])

term frequency and inverse document frequency(tf and idf)


In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer()
tfidf.fit(['hello everybody', 'everyone good','good day'])
tfidf.vocabulary_

{'hello': 4, 'everybody': 1, 'everyone': 2, 'good': 3, 'day': 0}

In [9]:
tfidf.transform(['hello good']).toarray()

array([[0.        , 0.        , 0.        , 0.60534851, 0.79596054]])

In [11]:
for t in tfidf.get_feature_names_out():
  temp=tfidf.vocabulary_[t]
  print(t, " : ",tfidf.idf_[temp])

day  :  1.6931471805599454
everybody  :  1.6931471805599454
everyone  :  1.6931471805599454
good  :  1.2876820724517808
hello  :  1.6931471805599454


Ngrams

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
bow= CountVectorizer(ngram_range=(2,2))
bow.fit(['hello everybody', 'everyone good','good day'])
bow.vocabulary_

{'hello everybody': 2, 'everyone good': 0, 'good day': 1}

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
bow= CountVectorizer(ngram_range=(1,3))
bow.fit(['hello everybody', 'everyone good','good day'])
bow.vocabulary_

{'hello': 6,
 'everybody': 1,
 'hello everybody': 7,
 'everyone': 2,
 'good': 4,
 'everyone good': 3,
 'day': 0,
 'good day': 5}

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
bow= CountVectorizer(ngram_range=(2,3))
bow.fit(['hello everybody', 'everyone good','good day'])
bow.vocabulary_

{'hello everybody': 2, 'everyone good': 0, 'good day': 1}

In [21]:
bow.transform(['hello good']).toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0]])